services:
  trading_bot:
    build: .
    container_name: trading_bot_container
    ports:
      - "8888:8000"   # FastAPI
      - "47902:8001"  # Prometheus
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
