services:
  trading_bot:
    build: .
    container_name: trading_bot_container
    ports:
      - "8888:8000"   # FastAPI
      - "47902:8001"  # Prometheus
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
