version: '3.8'

services:
  trading_bot:
    build: .
    container_name: trading_bot_container
    ports:
      - "8000:8000"
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
