name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: List installed packages (for debugging)
      run: pip list

    - name: List project structure (for debugging)
      run: |
        echo "Project Structure:"
        ls -R

    - name: Set PYTHONPATH and Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        echo "PYTHONPATH is set to: $PYTHONPATH"
        pytest --verbose --cov=src tests/

    - name: Build Docker image
      run: docker build -t kaholik/my-trading-bot:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push kaholik/my-trading-bot:latest

